//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM1._2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserAccount
    {
        [Key]
        public int UserID { get; set; }

        [Display(Name = "Imie")]
        [Required(ErrorMessage = "Imie jest wymagane!")]
        public string FirstName { get; set; }

        [Display(Name = "Nazwisko")]
        [Required(ErrorMessage = "Nazwisko jest wymagane!")]
        public string LastName { get; set; }

        [Display(Name = "E-mail")]
        [Required(ErrorMessage = "Email jest wymagany!")]
        [RegularExpression(@"^([\w-\.]+)@((\[[0-9]{1,3]\.)|(([\w-]+\.)+))([a-zA-Z{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Prosze wprowadzic poprawny Email!")]
        public string Email { get; set; }

        [Display(Name = "Nazwa uzytkownika")]
        [Required(ErrorMessage = "Nazwa uzytkownika jest wymagana!")]
        public string UserName { get; set; }

        [Display(Name = "Has³o")]
        [Required(ErrorMessage = "Haslo jest wymagane!")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "Haslo musi byæ takie samo!")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }

        public string Roles { get; set; }
    }
}
