//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM1._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDetail
    {
        public int RequestDetailsID { get; set; }
        public int RequestID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> StageNumber { get; set; }
        public Nullable<System.DateTime> StageDate { get; set; }
        public string StageDesc { get; set; }
        public Nullable<int> StageTime { get; set; }
    
        public virtual RequestTable RequestTable { get; set; }
    }
}
